version: "3"
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./custom_rabbitmq_config.conf:/etc/rabbitmq/rabbitmq.conf"
  DTUTokenManagement:
    build: DTUPayTokenManagement
    image: dtu_pay_token_management
    container_name: DTUPayTokenManagement
  DTUPayWebService:
    build: DTUPayWebService
    image: dtu_pay_web_service
    container_name: DTUPayWebService
    ports:
      - "8080:8080"