version: "3"
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    ports:
      - "5673:5673"
      - "15672:15672"
    volumes:
      - "./custom_rabbitmq_config.conf:/etc/rabbitmq/rabbitmq.conf"
  DTUPayWebService:
    build: DTUPayWebService
    image: dtu_pay_web_service
    container_name: DTUPayWebService
    ports:
      - "8080:8080"